# Generated by Django 5.2 on 2026-02-25 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0002_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="available",
            field=models.IntegerField(),
        ),
    ]
